#!/usr/bin/env bash
# ============================================================================
# generate_legacy_compat.sh — regenerate include/scicv_legacy_constants.h
#
# OpenCV 5 removed the legacy C API headers (core/types_c.h, imgproc/types_c.h,
# highgui_c.h, imgcodecs/legacy, videoio/legacy) that scicv wrapped to expose
# the classic CV_* constant names to Scilab. Those names are part of scicv's
# public surface (demos/tests/user scripts), so this script derives them from
# the INSTALLED modern OpenCV enums — every alias is `static const int
# CV_x = cv::MODERN;`, so the values always match the linked library and can
# never drift. Mechanical families are grepped from the headers; irregular
# renames are hand-mapped at the bottom.
#
#   ./generate_legacy_compat.sh [/path/to/opencv/include/opencvN]
# ============================================================================
set -euo pipefail

INC="${1:-}"
if [ -z "$INC" ]; then
  PC=/opt/homebrew/bin/pkg-config; command -v "$PC" >/dev/null || PC=pkg-config
  for name in opencv6 opencv5 opencv4 opencv; do
    if "$PC" --exists "$name" 2>/dev/null; then
      INC="$("$PC" --cflags "$name" | tr ' ' '\n' | sed -n 's/^-I//p' | head -1)"
      break
    fi
  done
fi
[ -d "$INC/opencv2" ] || { echo "ERROR: OpenCV include dir not found ($INC)" >&2; exit 1; }

OUT="$(cd "$(dirname "$0")" && pwd)/scicv_legacy_constants.i"

# Extract enum-member names for a prefix from a header: lines that begin (after
# whitespace) with the identifier followed by '=' or ',' — comment/doc mentions
# don't match, so every emitted name is a real enum member.
members() { # members <header> <prefix>
  grep -hoE "^\s*${2}[A-Za-z0-9_]*\s*[=,]" "$1" 2>/dev/null \
    | sed -E 's/^\s*//; s/\s*[=,]$//' | sort -u
}

emit() { # emit <legacy-name> <modern-expr>
  printf '%%constant int %s = %s;\n' "$1" "$2" >> "$OUT"
}

emit_family() { # emit_family <header> <modern-prefix> <legacy-prefix>
  local h="$1" mp="$2" lp="$3" n
  for n in $(members "$h" "$mp"); do
    emit "${lp}${n#"$mp"}" "cv::$n"
  done
}

cat > "$OUT" <<'HDR'
// Generated by generate_legacy_compat.sh — DO NOT EDIT BY HAND.
//
// Classic OpenCV C-API constant names (CV_*), aliased to the modern C++ enum
// values of the OpenCV this toolbox is built against. OpenCV 5 removed the
// legacy headers that used to provide them; these aliases keep scicv's
// public Scilab surface (demos, tests, user scripts) source-compatible.
// Registered as Scilab variables at module init, exactly like enum members.

HDR

IP="$INC/opencv2/imgproc.hpp"
CORE="$INC/opencv2/core.hpp"
BASE="$INC/opencv2/core/base.hpp"
IC="$INC/opencv2/imgcodecs.hpp"
VIO="$INC/opencv2/videoio.hpp"
HG="$INC/opencv2/highgui.hpp"

echo "// ---- imgproc ----" >> "$OUT"
emit_family "$IP" COLOR_          CV_          # CV_BGR2GRAY = cv::COLOR_BGR2GRAY, ...
emit_family "$IP" THRESH_         CV_THRESH_
emit_family "$IP" ADAPTIVE_THRESH_ CV_ADAPTIVE_THRESH_
emit_family "$IP" RETR_           CV_RETR_
emit_family "$IP" CHAIN_APPROX_   CV_CHAIN_APPROX_
emit_family "$IP" TM_             CV_TM_
emit_family "$IP" HOUGH_          CV_HOUGH_
emit_family "$IP" DIST_           CV_DIST_     # incl. DIST_LABEL_* / DIST_MASK_*
emit_family "$IP" HISTCMP_        CV_COMP_
emit_family "$IP" CONTOURS_MATCH_ CV_CONTOURS_MATCH_
emit_family "$IP" FLOODFILL_      CV_FLOODFILL_
emit_family "$IP" INTER_          CV_INTER_
emit "CV_INTER_NN" "cv::INTER_NEAREST"
emit "CV_WARP_FILL_OUTLIERS" "cv::WARP_FILL_OUTLIERS"
emit "CV_WARP_INVERSE_MAP" "cv::WARP_INVERSE_MAP"
# morphology: operations were CV_MOP_*, structuring shapes CV_SHAPE_*
for m in ERODE DILATE OPEN CLOSE GRADIENT TOPHAT BLACKHAT HITMISS; do
  emit "CV_MOP_$m" "cv::MORPH_$m"
done
emit "CV_SHAPE_RECT"    "cv::MORPH_RECT"
emit "CV_SHAPE_CROSS"   "cv::MORPH_CROSS"
emit "CV_SHAPE_ELLIPSE" "cv::MORPH_ELLIPSE"

echo "// ---- imgcodecs ----" >> "$OUT"
emit_family "$IC" IMWRITE_ CV_IMWRITE_
emit "CV_LOAD_IMAGE_UNCHANGED"          "cv::IMREAD_UNCHANGED"
emit "CV_LOAD_IMAGE_GRAYSCALE"          "cv::IMREAD_GRAYSCALE"
emit "CV_LOAD_IMAGE_COLOR"              "cv::IMREAD_COLOR"
emit "CV_LOAD_IMAGE_ANYDEPTH"           "cv::IMREAD_ANYDEPTH"
emit "CV_LOAD_IMAGE_ANYCOLOR"           "cv::IMREAD_ANYCOLOR"
emit "CV_LOAD_IMAGE_IGNORE_ORIENTATION" "cv::IMREAD_IGNORE_ORIENTATION"

echo "// ---- videoio ----" >> "$OUT"
emit_family "$VIO" CAP_PROP_ CV_CAP_PROP_
# pre-5 typo aliases are #if'd out for the compiler — map them to the fixed names
sed -i '' -E '/CV_CAP_PROP_GIGA_FRAME_(HEIGH_MAX|SENS_HEIGH) /d' "$OUT"
emit "CV_CAP_PROP_GIGA_FRAME_HEIGH_MAX"  "cv::CAP_PROP_GIGA_FRAME_HEIGHT_MAX"
emit "CV_CAP_PROP_GIGA_FRAME_SENS_HEIGH" "cv::CAP_PROP_GIGA_FRAME_SENS_HEIGHT"
emit_family "$VIO" CAP_      CV_CAP_          # backends (CAP_ANY, CAP_V4L2, ...); PROP dupes are distinct names
# CV_FOURCC itself still ships in OpenCV 5 core/cvdef.h (wrapped from there).

echo "// ---- highgui ----" >> "$OUT"
emit_family "$HG" WINDOW_   CV_WINDOW_
emit_family "$HG" WND_PROP_ CV_WND_PROP_
emit_family "$HG" EVENT_    CV_EVENT_
emit "CV_GUI_NORMAL"   "cv::WINDOW_GUI_NORMAL"
emit "CV_GUI_EXPANDED" "cv::WINDOW_GUI_EXPANDED"

echo "// ---- core ----" >> "$OUT"
emit_family "$CORE" SORT_  CV_SORT_
emit_family "$CORE" COVAR_ CV_COVAR_
emit_family "$CORE" REDUCE_ CV_REDUCE_
emit_family "$BASE" CMP_   CV_CMP_
emit "CV_GEMM_A_T" "cv::GEMM_1_T"
emit "CV_GEMM_B_T" "cv::GEMM_2_T"
emit "CV_GEMM_C_T" "cv::GEMM_3_T"
emit "CV_DXT_FORWARD"       "0"
emit "CV_DXT_INVERSE"       "cv::DFT_INVERSE"
emit "CV_DXT_SCALE"         "cv::DFT_SCALE"
emit "CV_DXT_INV_SCALE"     "cv::DFT_INVERSE + cv::DFT_SCALE"
emit "CV_DXT_INVERSE_SCALE" "cv::DFT_INVERSE + cv::DFT_SCALE"
emit "CV_DXT_ROWS"          "cv::DFT_ROWS"
emit "CV_C"      "cv::NORM_INF"
emit "CV_L1"     "cv::NORM_L1"
emit "CV_L2"     "cv::NORM_L2"
emit "CV_MINMAX" "cv::NORM_MINMAX"
emit "CV_RELATIVE_C"  "cv::NORM_RELATIVE | cv::NORM_INF"
emit "CV_RELATIVE_L1" "cv::NORM_RELATIVE | cv::NORM_L1"
emit "CV_RELATIVE_L2" "cv::NORM_RELATIVE | cv::NORM_L2"
emit "CV_LU"       "cv::DECOMP_LU"
emit "CV_SVD"      "cv::DECOMP_SVD"
emit "CV_SVD_SYM"  "cv::DECOMP_EIG"
emit "CV_CHOLESKY" "cv::DECOMP_CHOLESKY"
emit "CV_QR"       "cv::DECOMP_QR"
emit "CV_PCA_DATA_AS_ROW" "cv::PCA::DATA_AS_ROW"
emit "CV_PCA_DATA_AS_COL" "cv::PCA::DATA_AS_COL"
emit "CV_PCA_USE_AVG"     "cv::PCA::USE_AVG"
emit "CV_SVD_MODIFY_A"    "cv::SVD::MODIFY_A"
emit "CV_RAND_UNI"    "cv::RNG::UNIFORM"
emit "CV_RAND_NORMAL" "cv::RNG::NORMAL"
emit "CV_TERMCRIT_ITER"   "cv::TermCriteria::MAX_ITER"
emit "CV_TERMCRIT_NUMBER" "cv::TermCriteria::COUNT"
emit "CV_TERMCRIT_EPS"    "cv::TermCriteria::EPS"
emit "CV_KMEANS_USE_INITIAL_LABELS" "cv::KMEANS_USE_INITIAL_LABELS"
emit "CV_USRTYPE1" "7"   # historical deprecated alias (slot became CV_16F)

# Dedup: overlapping sweeps can emit the same legacy name twice (e.g. the CAP_
# backend family also matches CAP_PROP_*). Keep the first definition of each.
awk '!/^%constant int /{print;next}{split($0,a," ");if(!(a[3] in seen)){seen[a[3]]=1;print}}' "$OUT" > "$OUT.tmp" \
  && mv "$OUT.tmp" "$OUT"

echo "wrote $OUT ($(grep -c '%constant int' "$OUT") constants)"
