%include InputArray_typemaps.i
%include OutputArray_typemaps.i
%include Point_typemaps.i
%include Rect_typemaps.i
%include Size_typemaps.i
%include KeyPoint_typemaps.i
%include VectorRect_typemaps.i
%include float_ranges_typemaps.i
%include Mat_typemaps.i
